### ISSUE TITLE
can not find file "local"

### ISSUE THREAD

**Issue by tmlaes** [HFFP/brc20-example#2]
![image](https://github.com/HFFP/brc20-example/assets/16698843/df523b6b-7930-4621-815b-155c97a4d160)

**Comment by HFFP** [comment]
you need to apply a ApiKey by unisat
[apply](https://docs.unisat.io/dev/unisat-developer-service#getting-an-api-key)

**Comment by HFFP** [comment]
'local' just some privet info

![image](https://github.com/HFFP/brc20-example/assets/22065829/7c4a4ce6-5906-4e19-9ade-db0915e0349e)
